# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

services:
  peer0.org1.example.com:
    container_name: peer0.org1.example.com
    image: ${FABRIC_DOCKER_NS:-hyperledger}/fabric-peer:${FABRIC_IMAGE_TAG:-latest}
    labels:
      service: hyperledger-fabric
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
    volumes:
      - ./docker/peercfg:/etc/hyperledger/peercfg
      - ${DOCKER_SOCK}:/host/var/run/docker.sock

  peer0.org2.example.com:
    container_name: peer0.org2.example.com
    image: ${FABRIC_DOCKER_NS:-hyperledger}/fabric-peer:${FABRIC_IMAGE_TAG:-latest}
    labels:
      service: hyperledger-fabric
    environment:
      #Generic peer variables
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=fabric_test
    volumes:
      - ./docker/peercfg:/etc/hyperledger/peercfg
      - ${DOCKER_SOCK}:/host/var/run/docker.sock
